const ConfigurationBase = {
    prefix: "-",
    ownerId: "451619591320371213",
    designerId: "830226550116057149",
    contentManagerId: "315297741406339083",
    clientId: "837147659898191902",
    guildId: "952214872584749056",
    saphiresHome: "952214872584749056",
    guildCreateChannelId: "981017120206897182",
    guildDeleteChannelId: "981017074723852328",
    rifaChannel: "987408171708579870",
    LoteriaChannel: "987408234564452393",
    letterChannelReport: "980997922403541012",
    BugsChannelId: "980997977906745374",
    LogChannelId: "993893182951673860",
    PackageInvite: "https://discord.gg/UArp6eyvwu",
    SupportServerLink: "https://discord.gg/EyAUDpQaW9",
    MoonServerLink: "https://discord.gg/2EMVCbJxuC",
    GoogleForm: "https://forms.gle/4sQ1mgRdP4b1fUnx7",
    SaphiDocs: "https://saphire.gitbook.io/saphire/",
    TopGGLink: "https://top.gg/bot/912509487984812043/vote",
    statcordURL: "https://statcord.com/bot/",
    Terms: "https://saphire.gitbook.io/saphire/saphire/termos-de-servicos",
    guildsToPrivateCommands: [
        "986292524790464562",
        "888464632291917956",
        "882475447387054081",
        "818260805119377448",
        "952214872584749056"
    ]
}

const DiscordColors = {
    Default: "Padrão",
    White: "Branco",
    Aqua: "Água",
    Green: "Verde",
    Blue: "Azul",
    Yellow: "Amarelo",
    Purple: "Roxo",
    LuminousVividPink: "Rosa Vívido Luminoso",
    Fuchsia: "Fuchsia",
    Gold: "Ouro",
    Orange: "Laranja",
    Red: "Vermelho",
    Grey: "Cinza",
    Navy: "Oceano Apagado",
    DarkAqua: "Água Escura",
    DarkGreen: "Verde Escuro",
    DarkBlue: "Azul Escuro",
    DarkPurple: "Roxo Escuro",
    DarkVividPink: "Rosa Vívido Escuro",
    DarkGold: "Ouro Escuro",
    DarkOrange: "Laranja Escuro",
    DarkRed: "Vermelho Escuro",
    DarkGrey: "Cinza Escuro",
    DarkerGrey: "Cinza Mais Escuro",
    LightGrey: "Cinza Claro",
    DarkNavy: "Oceano Escuro",
    Blurple: "Violeta",
    Greyple: "Verde Acinzentado",
    DarkButNotBlack: "Escuro, mas não preto",
    NotQuiteBlack: "Não tão preto",
    LuminousVividRed: "Vermelho Vívido Luminoso"
}

const BitColors = {
    Default: 0x000000,
    White: 0xffffff,
    Aqua: 0x1abc9c,
    Green: 0x57f287,
    Blue: 0x3498db,
    Yellow: 0xfee75c,
    Purple: 0x9b59b6,
    LuminousVividPink: 0xe91e63,
    Fuchsia: 0xeb459e,
    Gold: 0xf1c40f,
    Orange: 0xe67e22,
    Red: 0xed4245,
    Grey: 0x95a5a6,
    Navy: 0x34495e,
    DarkAqua: 0x11806a,
    DarkGreen: 0x1f8b4c,
    DarkBlue: 0x206694,
    DarkPurple: 0x71368a,
    DarkVividPink: 0xad1457,
    DarkGold: 0xc27c0e,
    DarkOrange: 0xa84300,
    DarkRed: 0x992d22,
    DarkGrey: 0x979c9f,
    DarkerGrey: 0x7f8c8d,
    LightGrey: 0xbcc0c0,
    DarkNavy: 0x2c3e50,
    Blurple: 0x5865f2,
    Greyple: 0x99aab5,
    DarkButNotBlack: 0x2c2f33,
    NotQuiteBlack: 0x23272a,
    LuminousVividRed: 0xff0000
}

const Languages = {
    "pt-BR": "Português",
    af: "Africano",
    am: "Amárico",
    ar: "Arábico",
    az: "Azerbaijano",
    be: "Bielorrusso",
    bg: "Bulgariano",
    bn: "Bengali",
    bs: "Bosniano",
    ca: "Catalano",
    ceb: "Cebuano",
    co: "Corso",
    cs: "Tcheco",
    cy: "Galês",
    da: "Dinamarquês",
    de: "Alemão",
    el: "Grego",
    en: "Inglês",
    eo: "Esperanto",
    es: "Espanhol",
    et: "Estoniano",
    eu: "Basco",
    fa: "Persa",
    fi: "Finlandês",
    fr: "Francês",
    fy: "Frísio",
    ga: "Irlandês",
    gd: "Scots Gaelic",
    gl: "Gaélico Escocês",
    gu: "Gujarati",
    ha: "Hauçá",
    haw: "Hawaiano",
    he: "Hebraico",
    hi: "Hindi",
    hmn: "Hmong",
    hr: "Croata",
    ht: "Crioulo Haitiano",
    hu: "Húngaro",
    hy: "Armênio",
    id: "Indonésio",
    ig: "Ibo",
    is: "Islandês",
    it: "Italiano",
    iw: "Hebraico Antigo",
    ja: "Japanês",
    jw: "Javanês",
    ka: "Georgiano",
    kk: "Cazaque",
    km: "Khmer",
    kn: "Canarês",
    ko: "Koreano",
    ku: "Curdo (Kurmanji)",
    ky: "Quirguistão",
    la: "Latin",
    lb: "Luxemburguês",
    lo: "Laos",
    lt: "Lituano",
    lv: "Letão",
    mg: "Malgaxe",
    mi: "Maori",
    mk: "Macedônio",
    ml: "Malaiala",
    mn: "Mongol",
    mr: "Marathi",
    ms: "Malaio",
    mt: "Maltês",
    my: "Mianmar (Burmese)",
    ne: "Nepalês",
    nl: "Holandês",
    no: "Norueguês",
    ny: "Chichewa",
    pa: "Chichewa",
    pl: "Polonês",
    ps: "Pashto",
    pt: "Português",
    ro: "Romeno",
    ru: "Russo",
    sd: "Sindi",
    si: "Cingalês",
    sk: "Eslovaco",
    sl: "Esloveno",
    sm: "Samoano",
    sn: "Shona",
    so: "Somali",
    sq: "Albanês",
    sr: "Sérvio",
    st: "Sesotho",
    su: "Sundanês",
    sv: "Sueco",
    sw: "Suaíli",
    ta: "Tâmil",
    te: "Telugu",
    tg: "Tadjique",
    th: "Tailandês",
    tl: "Filipino",
    tr: "Turco",
    uk: "Ucraniano",
    ur: "Urdu",
    uz: "Uzbeque",
    vi: "Vietnamita",
    xh: "Xhosa",
    yi: "Iídiche",
    yo: "Iorubá",
    zu: "Zulu",
}

const Flags = {
    BotHTTPInteractions: "Bot de integração via HTTP",
    BugHunterLevel1: "Bug Hunter Level 1",
    BugHunterLevel2: "Bug Hunter Level 2",
    CertifiedModerator: "Moderador certificado pelo Discord",
    Hypesquad: "Membro do evento HypeSquad",
    HypeSquadOnlineHouse1: "Membro da House Bravery",
    HypeSquadOnlineHouse2: "Membro da House Brilliance",
    HypeSquadOnlineHouse3: "Membro da House Balance",
    Partner: "Proprietário de Servidor parceiro",
    PremiumEarlySupporter: "Apoiador Inicial",
    Quarantined: "Usuário em quarentana por atos recentes",
    Spammer: "Usuário punido por spam",
    Staff: "Empregado do Discord",
    TeamPseudoUser: "Usuário é uma equipe",
    VerifiedBot: "Bot Verificado",
    VerifiedDeveloper: "Desenvolvedor de bot inicial",
    DISCORD_EMPLOYEE: 'Empregado do Discord',
    DISCORD_PARTNER: 'Parceiro do Discord',
    HYPESQUAD_EVENTS: 'HypeSquad Events',
    HOUSE_BRAVERY: 'House of Bravery',
    HOUSE_BRILLIANCE: 'House of Brilliance',
    HOUSE_BALANCE: 'House of Balance',
    EARLY_SUPPORTER: 'Apoiador inicial',
    TEAM_USER: 'Usuário de Time',
    SYSTEM: 'Sistema',
    VERIFIED_BOT: 'Bot Verificado',
    VERIFIED_DEVELOPER: 'Verified Bot Developer',
    BOT_HTTP_INTERACTIONS: 'Bot de Interação HTTP'
}

const PermissionsAsFlagBits = {
    CreateInstantInvite: 1,
    KickMembers: 2,
    BanMembers: 4,
    Administrator: 8,
    ManageChannels: 16,
    ManageGuild: 32,
    AddReactions: 64,
    ViewAuditLog: 128,
    PrioritySpeaker: 256,
    Stream: 512,
    ViewChannel: 1024,
    SendMessages: 2048,
    SendTTSMessages: 4096,
    ManageMessages: 8192,
    EmbedLinks: 16384,
    AttachFiles: 32768,
    ReadMessageHistory: 65536,
    MentionEveryone: 131072,
    UseExternalEmojis: 262144,
    ViewGuildInsights: 524288,
    Connect: 1048576,
    Speak: 2097152,
    MuteMembers: 4194304,
    DeafenMembers: 8388608,
    MoveMembers: 16777216,
    UseVAD: 33554432,
    ChangeNickname: 67108864,
    ManageNicknames: 134217728,
    ManageRoles: 268435456,
    ManageWebhooks: 536870912,
    ManageEmojisAndStickers: 1073741824,
    UseApplicationCommands: 2147483648,
    RequestToSpeak: 4294967296,
    ManageEvents: 8589934592,
    ManageThreads: 17179869184,
    CreatePublicThreads: 34359738368,
    CreatePrivateThreads: 68719476736,
    UseExternalStickers: 137438953472,
    SendMessagesInThreads: 274877906944,
    UseEmbeddedActivities: 549755813888,
    ModerateMembers: 1099511627776
}

const PermissionsTranslate = {
    AddReactions: "Adicionar reações",
    Administrator: "Administrador",
    AttachFiles: "Anexar arquivos",
    BanMembers: "Banir membros",
    ChangeNickname: "Alterar apelido",
    Connect: "Conectar",
    CreateInstantInvite: "Criar convite",
    CreatePrivateThreads: "Criar tópicos privados",
    CreatePublicThreads: "Criar tópicos públicos",
    DeafenMembers: "Ensurdecer membros",
    EmbedLinks: "Inserir links",
    KickMembers: "Expulsar membros",
    ManageChannels: "Gerenciar canais",
    ManageEmojisAndStickers: "Gerenciar emojis e figurinhas",
    ManageEvents: "Gerenciar eventos",
    ManageGuild: "Gerenciar servidor",
    ManageMessages: "Gerenciar mensagens",
    ManageNicknames: "Gerenciar apelidos",
    ManageRoles: "Gerenciar cargos",
    ManageThreads: "Gerenciar tópicos",
    ManageWebhooks: "Gerenciar webhooks",
    MentionEveryone: "Mencionar everyone, here, e todos os cargos",
    ModerateMembers: "Membros de castigo",
    MoveMembers: "Mover membros",
    MuteMembers: "Silenciar membros",
    PrioritySpeaker: "Voz prioritária",
    ReadMessageHistory: "Ver histórico de mensagens",
    RequestToSpeak: "Pedir para falar",
    SendMessages: "Enviar mensagens",
    SendMessagesInThreads: "Enviar mensagens em tópicos",
    SendTTSMessages: "Enviar mensagens em Texto-para-voz",
    Speak: "Falar",
    UseEmbeddedActivities: "Começar atividades",
    Stream: "Vídeo",
    UseApplicationCommands: "Usar comandos de aplicativo",
    UseExternalEmojis: "Usar emojis externos",
    UseExternalStickers: "Usar figurinhas externas",
    UseVAD: "Usar detecção de voz",
    ViewAuditLog: "Ver o registro de auditoria",
    ViewChannel: "Ver canais",
    ViewGuildInsights: "Ver Análises do servidor"
  }

export {
    ConfigurationBase as Config,
    DiscordColors as ColorsTranslate,
    BitColors as Colors,
    Languages,
    Flags as DiscordFlags,
    PermissionsAsFlagBits as Permissions,
    PermissionsTranslate
}