const ConfigurationBase = {
    prefix: "-",
    ownerId: "451619591320371213",
    designerId: "830226550116057149",
    contentManagerId: "315297741406339083",
    clientId: "837147659898191902",
    guildId: "952214872584749056",
    guildPackageId: "882475447387054081",
    packageLogs: "1014911562894544916",
    saphiresHome: "952214872584749056",
    wallpaperIndicateChannelId: "1021089841460559983",
    guildCreateChannelId: "981017120206897182",
    guildDeleteChannelId: "981017074723852328",
    clientErrorChannelId: "1007819488584028180",
    rifaChannel: "987408171708579870",
    LoteriaChannel: "987408234564452393",
    letterChannelReport: "980997922403541012",
    BugsChannelId: "980997977906745374",
    LogChannelId: "993893182951673860",
    PackageInvite: "https://discord.gg/UArp6eyvwu",
    SupportServerLink: "https://discord.gg/EyAUDpQaW9",
    MoonServerLink: "https://discord.gg/2EMVCbJxuC",
    GoogleForm: "https://forms.gle/4sQ1mgRdP4b1fUnx7",
    SaphiDocs: "https://saphire.gitbook.io/saphire/",
    TopGGLink: "https://top.gg/bot/912509487984812043/vote",
    statcordURL: "https://statcord.com/bot/",
    Terms: "https://saphire.gitbook.io/saphire/saphire/termos-de-servicos",
    QrCodeWithoutPrice: "https://media.discordapp.net/attachments/893361065084198954/1007101315832360970/WhatsApp_Image_2022-08-10_at_10.39.05_PM.jpeg",
    ErrorWebhookProfileIcon: "https://media.discordapp.net/attachments/893361065084198954/1007839310772449400/Saphire_Panic.png",
    PackageLogsWebhookProfileIcon: "https://media.discordapp.net/attachments/893361065084198954/1018699630998986752/data-management.png?width=484&height=484",
    vocePrefereChannel: "1018945013016690708",
    guildsToPrivateCommands: [
        "986292524790464562",
        "888464632291917956",
        "882475447387054081",
        "818260805119377448",
        "952214872584749056"
    ]
}

const DiscordColors = {
    Default: "Padrão",
    White: "Branco",
    Aqua: "Água",
    Green: "Verde",
    Blue: "Azul",
    Yellow: "Amarelo",
    Purple: "Roxo",
    LuminousVividPink: "Rosa Vívido Luminoso",
    Fuchsia: "Fuchsia",
    Gold: "Ouro",
    Orange: "Laranja",
    Red: "Vermelho",
    Grey: "Cinza",
    Navy: "Oceano Apagado",
    DarkAqua: "Água Escura",
    DarkGreen: "Verde Escuro",
    DarkBlue: "Azul Escuro",
    DarkPurple: "Roxo Escuro",
    DarkVividPink: "Rosa Vívido Escuro",
    DarkGold: "Ouro Escuro",
    DarkOrange: "Laranja Escuro",
    DarkRed: "Vermelho Escuro",
    DarkGrey: "Cinza Escuro",
    DarkerGrey: "Cinza Mais Escuro",
    LightGrey: "Cinza Claro",
    DarkNavy: "Oceano Escuro",
    Blurple: "Violeta",
    Greyple: "Verde Acinzentado",
    DarkButNotBlack: "Escuro, mas não preto",
    NotQuiteBlack: "Não tão preto",
    LuminousVividRed: "Vermelho Vívido Luminoso"
}

const BitColors = {
    Default: 0x000000,
    White: 0xffffff,
    Aqua: 0x1abc9c,
    Green: 0x57f287,
    Blue: 0x3498db,
    Yellow: 0xfee75c,
    Purple: 0x9b59b6,
    LuminousVividPink: 0xe91e63,
    Fuchsia: 0xeb459e,
    Gold: 0xf1c40f,
    Orange: 0xe67e22,
    Red: 0xed4245,
    Grey: 0x95a5a6,
    Navy: 0x34495e,
    DarkAqua: 0x11806a,
    DarkGreen: 0x1f8b4c,
    DarkBlue: 0x206694,
    DarkPurple: 0x71368a,
    DarkVividPink: 0xad1457,
    DarkGold: 0xc27c0e,
    DarkOrange: 0xa84300,
    DarkRed: 0x992d22,
    DarkGrey: 0x979c9f,
    DarkerGrey: 0x7f8c8d,
    LightGrey: 0xbcc0c0,
    DarkNavy: 0x2c3e50,
    Blurple: 0x5865f2,
    Greyple: 0x99aab5,
    DarkButNotBlack: 0x2c2f33,
    NotQuiteBlack: 0x23272a,
    LuminousVividRed: 0xff0000
}

const HexColors = {
    Default: "#000000",
    White: "#ffffff",
    Aqua: "#1abc9c",
    Green: "#57f287",
    Blue: "#3498db",
    Yellow: "#fee75c",
    Purple: "#9b59b6",
    LuminousVividPink: "#e91e63",
    Fuchsia: "#eb459e",
    Gold: "#f1c40f",
    Orange: "#e67e22",
    Red: "#ed4245",
    Grey: "#95a5a6",
    Navy: "#34495e",
    DarkAqua: "#11806a",
    DarkGreen: "#1f8b4c",
    DarkBlue: "#206694",
    DarkPurple: "#71368a",
    DarkVividPink: "#ad1457",
    DarkGold: "#c27c0e",
    DarkOrange: "#a84300",
    DarkRed: "#992d22",
    DarkGrey: "#979c9f",
    DarkerGrey: "#7f8c8d",
    LightGrey: "#bcc0c0",
    DarkNavy: "#2c3e50",
    Blurple: "#5865f2",
    Greyple: "#99aab5",
    DarkButNotBlack: "#2c2f33",
    NotQuiteBlack: "#23272a",
    LuminousVividRed: "#ff0000"
}

const Languages = {
    af: "Africano",
    am: "Amárico",
    ar: "Arábico",
    az: "Azerbaijano",
    be: "Bielorrusso",
    bg: "Bulgariano",
    bn: "Bengali",
    bs: "Bosniano",
    ca: "Catalano",
    ceb: "Cebuano",
    co: "Corso",
    cs: "Tcheco",
    cy: "Galês",
    da: "Dinamarquês",
    de: "Alemão",
    el: "Grego",
    en: "Inglês",
    eo: "Esperanto",
    es: "Espanhol",
    et: "Estoniano",
    eu: "Basco",
    fa: "Persa",
    fi: "Finlandês",
    fr: "Francês",
    fy: "Frísio",
    ga: "Irlandês",
    gd: "Scots Gaelic",
    gl: "Gaélico Escocês",
    gu: "Gujarati",
    ha: "Hauçá",
    haw: "Hawaiano",
    he: "Hebraico",
    hi: "Hindi",
    hmn: "Hmong",
    hr: "Croata",
    ht: "Crioulo Haitiano",
    hu: "Húngaro",
    hy: "Armênio",
    id: "Indonésio",
    ig: "Ibo",
    is: "Islandês",
    it: "Italiano",
    iw: "Hebraico Antigo",
    ja: "Japanês",
    jw: "Javanês",
    ka: "Georgiano",
    kk: "Cazaque",
    km: "Khmer",
    kn: "Canarês",
    ko: "Koreano",
    ku: "Curdo (Kurmanji)",
    ky: "Quirguistão",
    la: "Latin",
    lb: "Luxemburguês",
    lo: "Laos",
    lt: "Lituano",
    lv: "Letão",
    mg: "Malgaxe",
    mi: "Maori",
    mk: "Macedônio",
    ml: "Malaiala",
    mn: "Mongol",
    mr: "Marathi",
    ms: "Malaio",
    mt: "Maltês",
    my: "Mianmar (Burmese)",
    ne: "Nepalês",
    nl: "Holandês",
    no: "Norueguês",
    ny: "Chichewa",
    pa: "Chichewa",
    pl: "Polonês",
    ps: "Pashto",
    pt: "Português",
    ro: "Romeno",
    ru: "Russo",
    sd: "Sindi",
    si: "Cingalês",
    sk: "Eslovaco",
    sl: "Esloveno",
    sm: "Samoano",
    sn: "Shona",
    so: "Somali",
    sq: "Albanês",
    sr: "Sérvio",
    st: "Sesotho",
    su: "Sundanês",
    sv: "Sueco",
    sw: "Suaíli",
    ta: "Tâmil",
    te: "Telugu",
    tg: "Tadjique",
    th: "Tailandês",
    tl: "Filipino",
    tr: "Turco",
    uk: "Ucraniano",
    ur: "Urdu",
    uz: "Uzbeque",
    vi: "Vietnamita",
    xh: "Xhosa",
    yi: "Iídiche",
    yo: "Iorubá",
    zu: "Zulu",
}

const Flags = {
    BotHTTPInteractions: "Bot de integração via HTTP",
    BugHunterLevel1: "Bug Hunter Level 1",
    BugHunterLevel2: "Bug Hunter Level 2",
    CertifiedModerator: "Moderador certificado pelo Discord",
    Hypesquad: "Membro do evento HypeSquad",
    HypeSquadOnlineHouse1: "Membro da House Bravery",
    HypeSquadOnlineHouse2: "Membro da House Brilliance",
    HypeSquadOnlineHouse3: "Membro da House Balance",
    Partner: "Proprietário de Servidor parceiro",
    PremiumEarlySupporter: "Apoiador Inicial",
    Quarantined: "Usuário em quarentana por atos recentes",
    Spammer: "Usuário punido por spam",
    Staff: "Empregado do Discord",
    TeamPseudoUser: "Usuário é uma equipe",
    VerifiedBot: "Bot Verificado",
    VerifiedDeveloper: "Desenvolvedor de bot inicial",
    DISCORD_EMPLOYEE: 'Empregado do Discord',
    DISCORD_PARTNER: 'Parceiro do Discord',
    HYPESQUAD_EVENTS: 'HypeSquad Events',
    HOUSE_BRAVERY: 'House of Bravery',
    HOUSE_BRILLIANCE: 'House of Brilliance',
    HOUSE_BALANCE: 'House of Balance',
    EARLY_SUPPORTER: 'Apoiador inicial',
    TEAM_USER: 'Usuário de Time',
    SYSTEM: 'Sistema',
    VERIFIED_BOT: 'Bot Verificado',
    VERIFIED_DEVELOPER: 'Verified Bot Developer',
    BOT_HTTP_INTERACTIONS: 'Bot de Interação HTTP'
}

const PermissionsAsFlagBits = {
    CreateInstantInvite: 1,
    KickMembers: 2,
    BanMembers: 4,
    Administrator: 8,
    ManageChannels: 16,
    ManageGuild: 32,
    AddReactions: 64,
    ViewAuditLog: 128,
    PrioritySpeaker: 256,
    Stream: 512,
    ViewChannel: 1024,
    SendMessages: 2048,
    SendTTSMessages: 4096,
    ManageMessages: 8192,
    EmbedLinks: 16384,
    AttachFiles: 32768,
    ReadMessageHistory: 65536,
    MentionEveryone: 131072,
    UseExternalEmojis: 262144,
    ViewGuildInsights: 524288,
    Connect: 1048576,
    Speak: 2097152,
    MuteMembers: 4194304,
    DeafenMembers: 8388608,
    MoveMembers: 16777216,
    UseVAD: 33554432,
    ChangeNickname: 67108864,
    ManageNicknames: 134217728,
    ManageRoles: 268435456,
    ManageWebhooks: 536870912,
    ManageEmojisAndStickers: 1073741824,
    UseApplicationCommands: 2147483648,
    RequestToSpeak: 4294967296,
    ManageEvents: 8589934592,
    ManageThreads: 17179869184,
    CreatePublicThreads: 34359738368,
    CreatePrivateThreads: 68719476736,
    UseExternalStickers: 137438953472,
    SendMessagesInThreads: 274877906944,
    UseEmbeddedActivities: 549755813888,
    ModerateMembers: 1099511627776
}

const DiscordPermissons = {
    AddReactions: "AddReactions",
    Administrator: "Administrator",
    AttachFiles: "AttachFiles",
    BanMembers: "BanMembers",
    ChangeNickname: "ChangeNickname",
    Connect: "Connect",
    CreateInstantInvite: "CreateInstantInvite",
    CreatePrivateThreads: "CreatePrivateThreads",
    CreatePublicThreads: "CreatePublicThreads",
    DeafenMembers: "DeafenMembers",
    EmbedLinks: "EmbedLinks",
    KickMembers: "KickMembers",
    ManageChannels: "ManageChannels",
    ManageEmojisAndStickers: "ManageEmojisAndStickers",
    ManageEvents: "ManageEvents",
    ManageGuild: "ManageGuild",
    ManageMessages: "ManageMessages",
    ManageNicknames: "ManageNicknames",
    ManageRoles: "ManageRoles",
    ManageThreads: "ManageThreads",
    ManageWebhooks: "ManageWebhooks",
    MentionEveryone: "MentionEveryone",
    ModerateMembers: "ModerateMembers",
    MoveMembers: "MoveMembers",
    MuteMembers: "MuteMembers",
    PrioritySpeaker: "PrioritySpeaker",
    ReadMessageHistory: "ReadMessageHistory",
    RequestToSpeak: "RequestToSpeak",
    SendMessages: "SendMessages",
    SendMessagesInThreads: "SendMessagesInThreads",
    SendTTSMessages: "SendTTSMessages",
    Speak: "Speak",
    UseEmbeddedActivities: "UseEmbeddedActivities",
    Stream: "Stream",
    UseApplicationCommands: "UseApplicationCommands",
    UseExternalEmojis: "UseExternalEmojis",
    UseExternalStickers: "UseExternalStickers",
    UseVAD: "UseVAD",
    ViewAuditLog: "ViewAuditLog",
    ViewChannel: "ViewChannel",
    ViewGuildInsights: "ViewGuildInsights"
}

const PermissionsTranslate = {
    AddReactions: "Adicionar reações",
    Administrator: "Administrador",
    AttachFiles: "Anexar arquivos",
    BanMembers: "Banir membros",
    ChangeNickname: "Alterar apelido",
    Connect: "Conectar",
    CreateInstantInvite: "Criar convite",
    CreatePrivateThreads: "Criar tópicos privados",
    CreatePublicThreads: "Criar tópicos públicos",
    DeafenMembers: "Ensurdecer membros",
    EmbedLinks: "Inserir links",
    KickMembers: "Expulsar membros",
    ManageChannels: "Gerenciar canais",
    ManageEmojisAndStickers: "Gerenciar emojis e figurinhas",
    ManageEvents: "Gerenciar eventos",
    ManageGuild: "Gerenciar servidor",
    ManageMessages: "Gerenciar mensagens",
    ManageNicknames: "Gerenciar apelidos",
    ManageRoles: "Gerenciar cargos",
    ManageThreads: "Gerenciar tópicos",
    ManageWebhooks: "Gerenciar webhooks",
    MentionEveryone: "Mencionar everyone, here, e todos os cargos",
    ModerateMembers: "Membros de castigo",
    MoveMembers: "Mover membros",
    MuteMembers: "Silenciar membros",
    PrioritySpeaker: "Voz prioritária",
    ReadMessageHistory: "Ver histórico de mensagens",
    RequestToSpeak: "Pedir para falar",
    SendMessages: "Enviar mensagens",
    SendMessagesInThreads: "Enviar mensagens em tópicos",
    SendTTSMessages: "Enviar mensagens em Texto-para-voz",
    Speak: "Falar",
    UseEmbeddedActivities: "Começar atividades",
    Stream: "Vídeo",
    UseApplicationCommands: "Usar comandos de aplicativo",
    UseExternalEmojis: "Usar emojis externos",
    UseExternalStickers: "Usar figurinhas externas",
    UseVAD: "Usar detecção de voz",
    ViewAuditLog: "Ver o registro de auditoria",
    ViewChannel: "Ver canais",
    ViewGuildInsights: "Ver Análises do servidor"
}

const DiscordErrors = {
    0: "General error",
    10001: "Unknown account",
    10002: "Unknown application",
    10003: "Unknown channel",
    10004: "Unknown guild",
    10005: "Unknown integration",
    10006: "Unknown invite",
    10007: "Unknown member",
    10008: "Unknown message",
    10009: "Unknown permission overwrite",
    10010: "Unknown provider",
    10011: "Unknown role",
    10012: "Unknown token",
    10013: "Unknown user",
    10014: "Unknown emoji",
    10015: "Unknown webhook",
    10016: "Unknown webhook service",
    10020: "Unknown session",
    10026: "Unknown ban",
    10027: "Unknown SKU",
    10028: "Unknown Store Listing",
    10029: "Unknown entitlement",
    10030: "Unknown build",
    10031: "Unknown lobby",
    10032: "Unknown branch",
    10033: "Unknown store directory layout",
    10036: "Unknown redistributable",
    10038: "Unknown gift code",
    10049: "Unknown stream",
    10050: "Unknown premium server subscribe cooldown",
    10057: "Unknown guild template",
    10059: "Unknown discoverable server category",
    10060: "Unknown sticker",
    10062: "Unknown interaction",
    10063: "Unknown application command",
    10065: "Unknown voice state",
    10066: "Unknown application command permissions",
    10067: "Unknown Stage Instance",
    10068: "Unknown Guild Member Verification Form",
    10069: "Unknown Guild Welcome Screen",
    10070: "Unknown Guild Scheduled Event",
    10071: "Unknown Guild Scheduled Event User",
    10087: "Unknown Tag",
    20001: "Bots cannot use this endpoint",
    20002: "Only bots can use this endpoint",
    20009: "Explicit content cannot be sent to the desired recipient(s)",
    20012: "You are not authorized to perform this action on this application",
    20016: "This action cannot be performed due to slowmode rate limit",
    20018: "Only the owner of this account can perform this action",
    20022: "This message cannot be edited due to announcement rate limits",
    20024: "Under minimum age",
    20028: "The channel you are writing has hit the write rate limit",
    20029: "The write action you are performing on the server has hit the write rate limit",
    20031: "Your Stage topic, server name, server description, or channel names contain words that are not allowed",
    20035: "Guild premium subscription level too low",
    30001: "Maximum number of guilds reached (100)",
    30002: "Maximum number of friends reached (1000)",
    30003: "Maximum number of pins reached for the channel (50)",
    30004: "Maximum number of recipients reached (10)",
    30005: "Maximum number of guild roles reached (250)",
    30007: "Maximum number of webhooks reached (10)",
    30008: "Maximum number of emojis reached",
    30010: "Maximum number of reactions reached (20)",
    30013: "Maximum number of guild channels reached (500)",
    30015: "Maximum number of attachments in a message reached (10)",
    30016: "Maximum number of invites reached (1000)",
    30018: "Maximum number of animated emojis reached",
    30019: "Maximum number of server members reached",
    30030: "Maximum number of server categories has been reached (5)",
    30031: "Guild already has a template",
    30032: "Maximum number of application commands reached",
    30033: "Max number of thread participants has been reached (1000)",
    30034: "Max number of daily application command creates has been reached (200)",
    30035: "Maximum number of bans for non-guild members have been exceeded",
    30037: "Maximum number of bans fetches has been reached",
    30038: "Maximum number of uncompleted guild scheduled events reached (100)",
    30039: "Maximum number of stickers reached",
    30040: "Maximum number of prune requests has been reached. Try again later",
    30042: "Maximum number of guild widget settings updates has been reached. Try again later",
    30046: "Maximum number of edits to messages older than 1 hour reached. Try again later",
    30047: "Maximum number of pinned threads in a forum channel has been reached",
    30048: "Maximum number of tags in a forum channel has been reached",
    30052: "Bitrate is too high for channel of this type",
    40001: "Unauthorized. Provide a valid token and try again",
    40002: "You need to verify your account in order to perform this action",
    40003: "You are opening direct messages too fast",
    40004: "Send messages has been temporarily disabled",
    40005: "Request entity too large. Try sending something smaller in size",
    40006: "This feature has been temporarily disabled server-side",
    40007: "The user is banned from this guild",
    40012: "Connection has been revoked",
    40032: "Target user is not connected to voice",
    40033: "This message has already been crossposted",
    40041: "An application command with that name already exists",
    40043: "Application interaction failed to send",
    40060: "Interaction has already been acknowledged",
    40061: "Tag names must be unique",
    50001: "Missing access",
    50002: "Invalid account type",
    50003: "Cannot execute action on a DM channel",
    50004: "Guild widget disabled",
    50005: "Cannot edit a message authored by another user",
    50006: "Cannot send an empty message",
    50007: "Cannot send messages to this user",
    50008: "Cannot send messages in a non-text channel",
    50009: "Channel verification level is too high for you to gain access",
    50010: "OAuth2 application does not have a bot",
    50011: "OAuth2 application limit reached",
    50012: "Invalid OAuth2 state",
    50013: "You lack permissions to perform that action",
    50014: "Invalid authentication token provided",
    50015: "Note was too long",
    50016: "Provided too few or too many messages to delete. Must provide at least 2 and fewer than 100 messages to delete",
    50017: "Invalid MFA Level",
    50019: "A message can only be pinned to the channel it was sent in",
    50020: "Invite code was either invalid or taken",
    50021: "Cannot execute action on a system message",
    50024: "Cannot execute action on this channel type",
    50025: "Invalid OAuth2 access token provided",
    50026: "Missing required OAuth2 scope",
    50027: "Invalid webhook token provided",
    50028: "Invalid role",
    50033: "Invalid Recipient(s)",
    50034: "A message provided was too old to bulk delete",
    50035: "Invalid form body (returned for both application/json and multipart/form-data bodies), or invalid Content-Type provided",
    50036: "An invite was accepted to a guild the application's bot is not in",
    50041: "Invalid API version provided",
    50045: "File uploaded exceeds the maximum size",
    50046: "Invalid file uploaded",
    50054: "Cannot self-redeem this gift",
    50055: "Invalid Guild",
    50068: "Invalid message type",
    50070: "Payment source required to redeem gift",
    50074: "Cannot delete a channel required for Community guilds",
    50080: "Cannot edit stickers within a message",
    50081: "Invalid sticker sent",
    50083: "Tried to perform an operation on an archived thread, such as editing a message or adding a user to the thread",
    50084: "Invalid thread notification settings",
    50085: "before value is earlier than the thread creation date",
    50086: "Community server channels must be text channels",
    50095: "This server is not available in your location",
    50097: "This server needs monetization enabled in order to perform this action",
    50101: "This server needs more boosts to perform this action",
    50109: "The request body contains invalid JSON.",
    50132: "Ownership cannot be transferred to a bot user",
    50138: "Failed to resize asset below the maximum size: 262144",
    50146: "Uploaded file not found.",
    50600: "You do not have permission to send this sticker.",
    60003: "Two factor is required for this operation",
    80004: "No users with DiscordTag exist",
    90001: "Reaction was blocked",
    110001: "Application not yet available. Try again later",
    130000: "API resource is currently overloaded. Try again a little later",
    150006: "The Stage is already open",
    160002: "Cannot reply without permission to read message history",
    160004: "A thread has already been created for this message",
    160005: "Thread is locked",
    160006: "Maximum number of active threads reached",
    160007: "Maximum number of active announcement threads reached",
    170001: "Invalid JSON for uploaded Lottie file",
    170002: "Uploaded Lotties cannot contain rasterized images such as PNG or JPEG",
    170003: "Sticker maximum framerate exceeded",
    170004: "Sticker frame count exceeds maximum of 1000 frames",
    170005: "Lottie animation maximum dimensions exceeded",
    170006: "Sticker frame rate is either too small or too large",
    170007: "Sticker animation duration exceeds maximum of 5 seconds",
    180000: "Cannot update a finished event",
    180002: "Failed to create stage needed for stage event",
    200000: "Message was blocked by automatic moderation",
    200001: "Title was blocked by automatic moderation",
    220003: "Webhooks can only create threads in forum channels"
}

const ErrorsToIgnore = [
    10003, // "Unknown channel",
    10007, // "Unknown member",
    10008, // "Unknown message",
    10011, // "Unknown role",
    10013, // "Unknown user",
    10014, // "Unknown emoji",
    10026, // "Unknown ban",
    10060, // "Unknown sticker",
    10062, // "Unknown interaction",
    20035, // "Guild premium subscription level too low",
    30003, // "Maximum number of pins reached for the channel (50)",
    30005, // "Maximum number of guild roles reached (250)",
    30007, // "Maximum number of webhooks reached (10)",
    30008, // "Maximum number of emojis reached",
    30010, // "Maximum number of reactions reached (20)",
    30013, // "Maximum number of guild channels reached (500)",
    30018, // "Maximum number of animated emojis reached",
    30030, // "Maximum number of server categories has been reached (5)",
    30032, // "Maximum number of application commands reached",
    30033, // "Max number of thread participants has been reached (1000)",
    30034, // "Max number of daily application command creates has been reached (200)",
    30035, // "Maximum number of bans for non-guild members have been exceeded",
    30037, // "Maximum number of bans fetches has been reached",
    30039, // "Maximum number of stickers reached",
    50007, // "Cannot send messages to this user",
    50008, // "Cannot send messages in a non-text channel",
    50016, // "Provided too few or too many messages to delete. Must provide at least 2 and fewer than 100 messages to delete",
    50028, // "Invalid role",
    50034, // "A message provided was too old to bulk delete",
    50074, // "Cannot delete a channel required for Community guilds",
    50080, // "Cannot edit stickers within a message",
    50081 // "Invalid sticker sent"
]

const ErrorResponse = {
    10003: "Canal desconhecido.",
    10007: "Membro desconhecido.",
    10008: "Mensagem desconhecida.",
    10011: "Cargo desconhecido.",
    10013: "Usuário desconhecido.",
    10014: "Emoji desconhecido.",
    10026: "Ban desconhecido.",
    10060: "Sticker desconhecido.",
    10062: "Interação desconhecida.",
    20035: "Nível de impulso insuficiente.",
    30003: "Número máximo de mensagens fixadas atingido. (50)",
    30005: "Número máximo de cargo criados atingido. (250)",
    30007: "Número máximo de webhooks criadas atingido. (10)",
    30008: "Número máximo de emojis atingidos.",
    30010: "Número máximo de reações atingida. (20)",
    30013: "Número máximo de canais atingido. (500)",
    30018: "Número máximo de emojis animados atingido.",
    30030: "Número máximo de categorias atingido. (5)",
    30033: "Número máximo de membros na thread alcançada (1000)",
    30035: "Número de banimentos de membros sem servidor atingido.",
    30037: "Maximum number of bans fetches has been reached",
    30039: "Número máximo de sticker criados atingido.",
    50007: "Não é possível enviar mensagens para este usuário.",
    50008: "Não é possível enviar mensagens em um canal que não seja de texto.",
    50028: "Cargo inválido.",
    50034: "As mensagens acima são muito antigadas para deletar.",
    50074: "Não é possível deletar canais configurados pela comunidade do servidor.",
    50080: "Não é possível editar um sticker dentro de uma mensagem.",
    50081: "Um sticker inválido foi enviado."
}

export {
    ConfigurationBase as Config,
    DiscordColors as ColorsTranslate,
    BitColors as Colors,
    HexColors,
    Languages,
    Flags as DiscordFlags,
    PermissionsAsFlagBits as Permissions,
    PermissionsTranslate,
    DiscordErrors,
    DiscordPermissons,
    ErrorsToIgnore,
    ErrorResponse
}