const ConfigurationBase = {
    prefix: "-",
    ownerId: "451619591320371213",
    designerId: "830226550116057149",
    contentManagerId: "315297741406339083",
    clientId: "837147659898191902",
    guildId: "952214872584749056",
    saphiresHome: "952214872584749056",
    guildCreateChannelId: "981017120206897182",
    guildDeleteChannelId: "981017074723852328",
    rifaChannel: "987408171708579870",
    LoteriaChannel: "987408234564452393",
    letterChannelReport: "980997922403541012",
    BugsChannelId: "980997977906745374",
    LogChannelId: "980998008080572426",
    PackageInvite: "https://discord.gg/UArp6eyvwu",
    SupportServerLink: "https://discord.gg/EyAUDpQaW9",
    MoonServerLink: "https://discord.gg/2EMVCbJxuC",
    GoogleForm: "https://forms.gle/4sQ1mgRdP4b1fUnx7",
    SaphiDocs: "https://saphire.gitbook.io/saphire/",
    TopGGLink: "https://top.gg/bot/912509487984812043/vote",
    statcordURL: "https://statcord.com/bot/",
    Terms: "https://saphire.gitbook.io/saphire/saphire/termos-de-servicos",
    guildsToPrivateCommands: [
        "986292524790464562",
        "888464632291917956",
        "882475447387054081",
        "818260805119377448",
        "952214872584749056"
    ]
}

const DiscordColors = {
    Default: "Padrão",
    White: "Branco",
    Aqua: "Água",
    Green: "Verde",
    Blue: "Azul",
    Yellow: "Amarelo",
    Purple: "Roxo",
    LuminousVividPink: "Rosa Vívido Luminoso",
    Fuchsia: "Fuchsia",
    Gold: "Ouro",
    Orange: "Laranja",
    Red: "Vermelho",
    Grey: "Cinza",
    Navy: "Oceano Apagado",
    DarkAqua: "Água Escura",
    DarkGreen: "Verde Escuro",
    DarkBlue: "Azul Escuro",
    DarkPurple: "Roxo Escuro",
    DarkVividPink: "Rosa Vívido Escuro",
    DarkGold: "Ouro Escuro",
    DarkOrange: "Laranja Escuro",
    DarkRed: "Vermelho Escuro",
    DarkGrey: "Cinza Escuro",
    DarkerGrey: "Cinza Mais Escuro",
    LightGrey: "Cinza Claro",
    DarkNavy: "Oceano Escuro",
    Blurple: "Violeta",
    Greyple: "Verde Acinzentado",
    DarkButNotBlack: "Escuro, mas não preto",
    NotQuiteBlack: "Não tão preto",
    LuminousVividRed: "Vermelho Vívido Luminoso"
}

const BitColors = {
    Default: 0x000000,
    White: 0xffffff,
    Aqua: 0x1abc9c,
    Green: 0x57f287,
    Blue: 0x3498db,
    Yellow: 0xfee75c,
    Purple: 0x9b59b6,
    LuminousVividPink: 0xe91e63,
    Fuchsia: 0xeb459e,
    Gold: 0xf1c40f,
    Orange: 0xe67e22,
    Red: 0xed4245,
    Grey: 0x95a5a6,
    Navy: 0x34495e,
    DarkAqua: 0x11806a,
    DarkGreen: 0x1f8b4c,
    DarkBlue: 0x206694,
    DarkPurple: 0x71368a,
    DarkVividPink: 0xad1457,
    DarkGold: 0xc27c0e,
    DarkOrange: 0xa84300,
    DarkRed: 0x992d22,
    DarkGrey: 0x979c9f,
    DarkerGrey: 0x7f8c8d,
    LightGrey: 0xbcc0c0,
    DarkNavy: 0x2c3e50,
    Blurple: 0x5865f2,
    Greyple: 0x99aab5,
    DarkButNotBlack: 0x2c2f33,
    NotQuiteBlack: 0x23272a,
    LuminousVividRed: 0xff0000
}

const Languages = {
    "pt-BR": "Português",
    af: "Africano",
    am: "Amárico",
    ar: "Arábico",
    az: "Azerbaijano",
    be: "Bielorrusso",
    bg: "Bulgariano",
    bn: "Bengali",
    bs: "Bosniano",
    ca: "Catalano",
    ceb: "Cebuano",
    co: "Corso",
    cs: "Tcheco",
    cy: "Galês",
    da: "Dinamarquês",
    de: "Alemão",
    el: "Grego",
    en: "Inglês",
    eo: "Esperanto",
    es: "Espanhol",
    et: "Estoniano",
    eu: "Basco",
    fa: "Persa",
    fi: "Finlandês",
    fr: "Francês",
    fy: "Frísio",
    ga: "Irlandês",
    gd: "Scots Gaelic",
    gl: "Gaélico Escocês",
    gu: "Gujarati",
    ha: "Hauçá",
    haw: "Hawaiano",
    he: "Hebraico",
    hi: "Hindi",
    hmn: "Hmong",
    hr: "Croata",
    ht: "Crioulo Haitiano",
    hu: "Húngaro",
    hy: "Armênio",
    id: "Indonésio",
    ig: "Ibo",
    is: "Islandês",
    it: "Italiano",
    iw: "Hebraico Antigo",
    ja: "Japanês",
    jw: "Javanês",
    ka: "Georgiano",
    kk: "Cazaque",
    km: "Khmer",
    kn: "Canarês",
    ko: "Koreano",
    ku: "Curdo (Kurmanji)",
    ky: "Quirguistão",
    la: "Latin",
    lb: "Luxemburguês",
    lo: "Laos",
    lt: "Lituano",
    lv: "Letão",
    mg: "Malgaxe",
    mi: "Maori",
    mk: "Macedônio",
    ml: "Malaiala",
    mn: "Mongol",
    mr: "Marathi",
    ms: "Malaio",
    mt: "Maltês",
    my: "Mianmar (Burmese)",
    ne: "Nepalês",
    nl: "Holandês",
    no: "Norueguês",
    ny: "Chichewa",
    pa: "Chichewa",
    pl: "Polonês",
    ps: "Pashto",
    pt: "Português",
    ro: "Romeno",
    ru: "Russo",
    sd: "Sindi",
    si: "Cingalês",
    sk: "Eslovaco",
    sl: "Esloveno",
    sm: "Samoano",
    sn: "Shona",
    so: "Somali",
    sq: "Albanês",
    sr: "Sérvio",
    st: "Sesotho",
    su: "Sundanês",
    sv: "Sueco",
    sw: "Suaíli",
    ta: "Tâmil",
    te: "Telugu",
    tg: "Tadjique",
    th: "Tailandês",
    tl: "Filipino",
    tr: "Turco",
    uk: "Ucraniano",
    ur: "Urdu",
    uz: "Uzbeque",
    vi: "Vietnamita",
    xh: "Xhosa",
    yi: "Iídiche",
    yo: "Iorubá",
    zu: "Zulu",
}

export {
    ConfigurationBase as Config,
    DiscordColors as ColorsTranslate,
    BitColors as Colors,
    Languages
}